name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check PR title
        run: |
          MESSAGE="${{ github.event.pull_request.title }}"
          echo "Analyzed text: '$MESSAGE'"

          COMMIT_REGEX="^(feat|fix|chore|test)\(.+\): .+$"
          
          if [[ "$MESSAGE" =~ $COMMIT_REGEX ]]; then
            echo "Format is valid."
          else
            echo "Format is invalid."
            echo "Expected format: type(scope): message"
            echo "Allowed types: feat, fix, chore, test"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: |
          npm install
          npm run build