name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check commit message
        run: |
          LAST_COMMIT="${{ github.event.head_commit.message }}"
          COMMIT_REGEX="^(feat|fix|chore|test)\(.+\): .+$"
          
          if [[ "$LAST_COMMIT" =~ $COMMIT_REGEX ]]; then
            echo "Commit format is valid."
          else
            echo "Commit format is invalid."
            echo "Expected format: type(scope): message (allowed types: feat, fix, chore, test)"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: |
          npm install
          npm run build